name: "Dish_technologies"
version: 2

profile: "Dish_technologies"

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
test-paths: ["tests"]

models:
  Dish_technologies:
    gold:
      +schema: GOLD
      +materialized: table

    silver:
      +schema: SILVER
      +materialized: view
